### PR TITLE
migrated to nnbd.

### PR DESCRIPTION
**Pull request by bsutton**
Phil, 
love your package and I'm hoping to use it.

I've just migrated it to nndb.

I'm hoping you will take this PR and publish a new 2.x version.

Regards,
Brett

### CODE REVIEW

**Comment by pschiffmann** [comment]
Hi Brett,
thanks so much for the PR and the kind words! :)
I haven't worked with Dart for almost two years now, and haven't kept up with the language development, e.g. nnbd. (I know it exists, but haven't looked into how it works). I may find time over the holidays to catch up on that. Since you already published the `zone_di2` package, I hope it's not time critical ...
If you want to take over maintenance for the package, I can give you the pub package name (I don't know how that works, but I assume there is way to do it.)

I have one question regarding the `injectNullable` API change you made: Couldn't you specify the nullability directly in the token, like `const nullableToken = Token<string?>(); const nonNullableToken = Token<string>();`? ... Maybe I can answer that question myself after I read up on how nnbd works in Dart :D 

Best regards
Philipp

**Comment by bsutton** [comment]
Good thinking 99.

I handn't even considered that.
I'm in the process of rewriting.
If you are happy to transfer the pub.dev then I'm happy to take over the maintenance.

**Comment by bsutton** [comment]
If you can transfer it to:
https://pub.dev/publishers/noojee.dev

**Comment by pschiffmann** [comment]
I just looked into how I could transfer the package name to you. pub.dev offers me two options:
1. I can add you as an uploader, you just need to tell me your preferred email address.
2. I can transfer the package to a publisher, but I need to be a member of that publisher. I can do that if you can invite me (temporarily) to noojee.dev publisher.

**Comment by bsutton** [comment]
Phillipp,
just a courtesy email.

I ended up renaming the package to scope.

Whilst the core is based on your work I've completely re-written the api.
It started out as an effort to improve type safety and end up somewhere
else.

If you are interested:
https://pub.dev/packages/scope/score



S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by pschiffmann** [comment]
Sounds good, thanks for the update. I'll close this PR then. Best of luck with the package, and thanks for keeping the idea alive! :)

**Pull request closed without merging**
